# py manage.py makemigrations
# py manage.py migrate
# py manage.py shell 
# from news.models import *
# user1 = User.objects.create(username='Daniil123', first_name='Dan')
# user2 = User.objects.create(username='Mihail1', first_name='Misha') 
# Author.objects.create(users=user1)
# Author.objects.create(users=user2)
# Category.objects.create(category='Cars')
# Category.objects.create(category='Animals') 
# Category.objects.create(category='Education') 
# Category.objects.create(category='Science')   
# Post.objects.create(postAuthor=Author.objects.get(users=User.objects.get(username='Daniil123')), categoryType='NW', heading='news 1', text_Post = 'about news 1', rating_Post=0)
# Post.objects.create(postAuthor=Author.objects.get(users=User.objects.get(username='Daniil123')), categoryType='AR', heading='article 1', text_Post = 'about ar 1', rating_Post=0)
# Post.objects.create(postAuthor=Author.objects.get(users=User.objects.get(username='Mihail1')), categoryType='AR', heading='article 2',  text_Post = 'about ar 2', rating_Post=0)
# post1=Post.objects.get(pk=1) 
# post2=Post.objects.get(pk=2) 
# post3=Post.objects.get(pk=3) 
# category1=Category.objects.get(pk=4)
# category2=Category.objects.get(pk=4)
# category3=Category.objects.get(pk=4)
# category4=Category.objects.get(pk=4)
# post1.postCategory.add(category1) 
# post1.postCategory.add(category2) 
# post2.postCategory.add(category3) 
# post3.postCategory.add(category4,category1)
# Comment.objects.create(text_Comment='text comment1',commentUser=User.objects.get(username='Daniil123'),commentPost=Post.objects.get(pk=1))
# Comment.objects.create(text_Comment='text comment2',commentUser=User.objects.get(username='Daniil123'),commentPost=Post.objects.get(pk=2))
# Comment.objects.create(text_Comment='text comment3',commentUser=User.objects.get(username='Daniil123'),commentPost=Post.objects.get(pk=3))
# Comment.objects.create(text_Comment='text comment4',commentUser=User.objects.get(username='Mihail1'),commentPost=Post.objects.get(pk=3))
# post1.like()
# post1.like()
# post1.like()
# post1.like()
# post1.dislike()
# post2.like()
# post2.like()
# post2.like()
# post2.like()
# post2.like()
# post3.like() 
# post3.like()
# post3.like()
# post3.like()
# post3.like()
# post3.dislike() 
# Comment.objects.get(pk=1).like()
# Comment.objects.get(pk=1).like()
# Comment.objects.get(pk=2).like() 
# Comment.objects.get(pk=2).like()
# Comment.objects.get(pk=2).like()
# Comment.objects.get(pk=2).like()
# Comment.objects.get(pk=3).like() 
# Comment.objects.get(pk=3).like() 
# Comment.objects.get(pk=4).like() 
# Comment.objects.get(pk=4).like()
# Comment.objects.get(pk=4).dislike()
# Author.objects.get(users = User.objects.get(username="Daniil123")).update_rating()
# Author.objects.get(users = User.objects.get(username="Mihail1")).update_rating()  
# //print(Author.objects.all().order_by('-rating_Author').values('users', 'rating_Author')[0])//
# a = Author.objects.order_by('-rating_Author').first()  
# print(f'Имя пользователя: {a.users.username}, Рейтинг: {a.rating_Author}')     
# best_post=Post.objects.order_by('-rating_Post').first() 
# print(f'Автор: {best_post.postAuthor.users.username}, Рейтинг: {best_post.rating_Post}, Заголовок: {best_post.heading}, Превью: {best_post.preview()}, Время: {best_post.date} ')
# print(Comment.objects.filter(commentPost=best_post.id).values('text_Comment','date_Comment','rating_Comment','commentUser__username'))
#
#